export const kitchenMusic = new Audio("./assets/kichen-timer.mp3");
export const forest = new Audio("./assets/Floresta.wav");
export const rain = new Audio("./assets/Chuva.wav");
export const cafe = new Audio("./assets/Cafeteria.wav");
export const bonfire = new Audio("./assets/Lareira.wav"); 
forest.loop = true;
rain.loop = true;
cafe.loop = true;
bonfire.loop = true;